version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - github-actions
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: pnpm/action-setup
        versions:
          - '>=6.0.0'
