import type { PartialTokenSet } from './types';

/**
 * Names of built-in theme presets.
 *
 * Naming convention: `<kind>-<flavour>`. The `<kind>` prefix maps to the
 * default globe kind via `kinds/registry.ts → PRESET_DEFAULT_KIND`, so a
 * user picking `'dotted-dark'` gets the dotted kind automatically.
 */
export type ThemePresetName =
  | 'cinematic-night'
  | 'cinematic-day'
  | 'cinematic-dawn'
  | 'cinematic-noir'
  | 'outline-dark'
  | 'outline-light'
  | 'outline-sunset'
  | 'outline-cyber'
  | 'outline-monochrome'
  | 'dotted-dark'
  | 'wireframe-tron'
  | 'paper-default'
  | 'hologram-cyan';

/**
 * Built-in theme presets — each is a `Partial<TokenSet>` that only declares
 * the tokens that matter for that preset's identity. `resolveTheme()` merges
 * the partial over `DEFAULT_TOKENS` so callers always see a complete token
 * set.
 *
 * `outline-dark` is the studio's first-impression preset — every override
 * here is dialled to make the boot frame read as cinema rather than
 * tutorial: deep-space background, subtly-lifted ocean, vibrant cyan-
 * tinted borders with an additive glow, oversized atmosphere halo,
 * dense multi-tone starfield, and label halos that read on the dark
 * surface without fighting the country strokes. Other presets only
 * override what differs from `DEFAULT_TOKENS`.
 */
export const THEME_PRESETS: Readonly<Record<ThemePresetName, PartialTokenSet>> = Object.freeze({
  // Cinematic kind — night-earth hero look: dark oceans, warm land/city
  // detail, blue-white limb light, and restrained gold data overlays.
  'cinematic-night': Object.freeze({
    'background.color': '#02050b',
    'globe.surfaceColor': '#031622',
    'countries.border.color': '#f6b44d',
    'countries.border.opacity': 0.78,
    'countries.borderHover.color': '#fff0b8',
    'countries.borderHover.width': 2.2,
    'countries.borderHover.glowColor': '#ffc85a',
    'countries.borderHover.glowOpacity': 0.42,
    'countries.borderActive.color': '#7df9ff',
    'countries.fill.defaultColor': '#6e4724',
    'countries.fill.opacity': 0.24,
    'countries.label.color': '#d7e8ff',
    'countries.label.fontSize': 11,
    'countries.label.fontWeight': '500',
    'countries.label.textShadow':
      '0 0 4px rgba(0, 5, 12, 0.92), 0 0 10px rgba(246, 180, 77, 0.35)',
    'tooltip.backgroundColor': 'rgba(3, 7, 14, 0.92)',
    'tooltip.textColor': '#fff0b8',
    'lights.ambient.intensity': 0.34,
    'lights.directional.intensity': 1.2,
    'markers.defaultColor': '#ffd36a',
    'atmosphere.color': '#8bd8ff',
    'atmosphere.intensity': 1.25,
    'starfield.color': '#d8ecff',
    'starfield.density': 1800,
    'starfield.size': 1.1,
    'arcs.color': '#f6b44d',
    'arcs.width': 1.35,
    'arcs.opacity': 0.86,
    'arcs.headColor': '#7df9ff',
    'cinematic.oceanColor': '#021018',
    'cinematic.landColor': '#7a5328',
    'cinematic.cloudColor': '#cfeeff',
    'cinematic.nightColor': '#01040a',
    'cinematic.lightDirectionX': -0.62,
    'cinematic.lightDirectionY': 0.55,
    'cinematic.lightDirectionZ': 0.55,
    'cinematic.terminatorSoftness': 0.42,
    'cinematic.terminatorContrast': 1.45,
    'cinematic.keyIntensity': 1.6,
    'cinematic.fillIntensity': 0.1,
    'cinematic.rimColor': '#9bdaff',
    'cinematic.rimIntensity': 1.42,
    'cinematic.rimPower': 2.55,
    'cinematic.specularIntensity': 0.95,
    'cinematic.cityLightColor': '#ffe5a8',
    'cinematic.cityLightIntensity': 1.4,
    'cinematic.networkColor': '#f7c466',
    'cinematic.networkOpacity': 0.22,
    'cinematic.borderColor': '#f6b44d',
    'cinematic.borderIntensity': 1.08,
  }),

  // Blue-Marble daylight hero: sun from the front-right, bright oceans,
  // natural biomes, data accents kept gentle so the planet leads.
  'cinematic-day': Object.freeze({
    'background.color': '#02060f',
    'globe.surfaceColor': '#0b3a6e',
    'lights.ambient.intensity': 0.34,
    'lights.directional.intensity': 1.2,
    'markers.defaultColor': '#ffd27a',
    'atmosphere.color': '#8fd0ff',
    'atmosphere.intensity': 1.35,
    'starfield.color': '#e6f0ff',
    'starfield.density': 1400,
    'starfield.size': 1.0,
    'arcs.color': '#ffd27a',
    'arcs.width': 1.3,
    'arcs.opacity': 0.8,
    'arcs.headColor': '#ffffff',
    'tooltip.backgroundColor': 'rgba(3, 7, 14, 0.92)',
    'tooltip.textColor': '#fff0b8',
    'cinematic.oceanColor': '#0b3a6e',
    'cinematic.landColor': '#8a7a52',
    'cinematic.cloudColor': '#ffffff',
    'cinematic.nightColor': '#020a16',
    'cinematic.lightDirectionX': 0.66,
    'cinematic.lightDirectionY': 0.42,
    'cinematic.lightDirectionZ': 0.62,
    'cinematic.terminatorSoftness': 0.36,
    'cinematic.terminatorContrast': 1.3,
    'cinematic.keyIntensity': 1.9,
    'cinematic.fillIntensity': 0.16,
    'cinematic.rimColor': '#bfe6ff',
    'cinematic.rimIntensity': 1.1,
    'cinematic.rimPower': 2.8,
    'cinematic.specularIntensity': 1.1,
    'cinematic.cityLightColor': '#ffe0a0',
    'cinematic.cityLightIntensity': 0.9,
    'cinematic.networkColor': '#ffd58a',
    'cinematic.networkOpacity': 0.16,
    'cinematic.borderColor': '#ffe2a8',
    'cinematic.borderIntensity': 0.7,
    'cinematic.iceColor': '#eef6ff',
    'cinematic.vegetationColor': '#3d6b34',
    'cinematic.desertColor': '#d2b078',
    'cinematic.shallowWaterColor': '#2fa8c2',
    'cinematic.sunColor': '#fff6e0',
    'cinematic.saturation': 1.08,
  }),

  // Terminator-centred: a grazing sun from the left drags a long warm
  // twilight band across the disc; long ocean glint, warm data accents.
  'cinematic-dawn': Object.freeze({
    'background.color': '#03050a',
    'globe.surfaceColor': '#061a2e',
    'lights.ambient.intensity': 0.3,
    'lights.directional.intensity': 1.1,
    'markers.defaultColor': '#ffd9a0',
    'atmosphere.color': '#ffb27a',
    'atmosphere.intensity': 1.4,
    'starfield.color': '#dfe9ff',
    'starfield.density': 1900,
    'starfield.size': 1.1,
    'arcs.color': '#ffb86b',
    'arcs.width': 1.35,
    'arcs.opacity': 0.86,
    'arcs.headColor': '#fff1c9',
    'tooltip.backgroundColor': 'rgba(10, 6, 3, 0.92)',
    'tooltip.textColor': '#ffe6c4',
    'cinematic.oceanColor': '#061a2e',
    'cinematic.landColor': '#7a5a3a',
    'cinematic.cloudColor': '#ffe6d0',
    'cinematic.nightColor': '#040711',
    'cinematic.lightDirectionX': -0.95,
    'cinematic.lightDirectionY': 0.18,
    'cinematic.lightDirectionZ': 0.25,
    'cinematic.terminatorSoftness': 0.46,
    'cinematic.terminatorContrast': 1.2,
    'cinematic.keyIntensity': 1.55,
    'cinematic.fillIntensity': 0.08,
    'cinematic.rimColor': '#ffc48a',
    'cinematic.rimIntensity': 1.35,
    'cinematic.rimPower': 2.3,
    'cinematic.specularIntensity': 1.2,
    'cinematic.cityLightColor': '#ffd9a0',
    'cinematic.cityLightIntensity': 1.5,
    'cinematic.networkColor': '#ffd18a',
    'cinematic.networkOpacity': 0.24,
    'cinematic.borderColor': '#ffb86b',
    'cinematic.borderIntensity': 1.1,
    'cinematic.desertColor': '#d8a96a',
    'cinematic.shallowWaterColor': '#2c8fa4',
    'cinematic.sunColor': '#ffe7c2',
    'cinematic.moonColor': '#9fb8ff',
  }),

  // Desaturated, hard-edged monochrome planet with pure-white data accents.
  'cinematic-noir': Object.freeze({
    'background.color': '#050608',
    'globe.surfaceColor': '#0a0d12',
    'lights.ambient.intensity': 0.3,
    'lights.directional.intensity': 1.2,
    'markers.defaultColor': '#ffffff',
    'atmosphere.color': '#dfe8f2',
    'atmosphere.intensity': 1.1,
    'starfield.color': '#ffffff',
    'starfield.density': 1600,
    'starfield.size': 1.0,
    'arcs.color': '#ffffff',
    'arcs.width': 1.2,
    'arcs.opacity': 0.9,
    'arcs.headColor': '#ffffff',
    'tooltip.backgroundColor': 'rgba(4, 5, 7, 0.94)',
    'tooltip.textColor': '#f2f4f7',
    'cinematic.oceanColor': '#0a0d12',
    'cinematic.landColor': '#8c8c8c',
    'cinematic.cloudColor': '#e8e8e8',
    'cinematic.nightColor': '#030405',
    'cinematic.lightDirectionX': -0.7,
    'cinematic.lightDirectionY': 0.5,
    'cinematic.lightDirectionZ': 0.45,
    'cinematic.terminatorSoftness': 0.3,
    'cinematic.terminatorContrast': 1.7,
    'cinematic.keyIntensity': 1.8,
    'cinematic.fillIntensity': 0.05,
    'cinematic.rimColor': '#cfd8e3',
    'cinematic.rimIntensity': 1.3,
    'cinematic.rimPower': 3.0,
    'cinematic.specularIntensity': 1.3,
    'cinematic.cityLightColor': '#fff4d6',
    'cinematic.cityLightIntensity': 1.7,
    'cinematic.networkColor': '#e8eef5',
    'cinematic.networkOpacity': 0.28,
    'cinematic.borderColor': '#dfe6ee',
    'cinematic.borderIntensity': 1.2,
    'cinematic.iceColor': '#f2f4f7',
    'cinematic.vegetationColor': '#3a4a3c',
    'cinematic.desertColor': '#8f8a7c',
    'cinematic.shallowWaterColor': '#3f5561',
    'cinematic.auroraColor': '#9ad0ff',
    'cinematic.auroraTopColor': '#b8c4ff',
    'cinematic.moonColor': '#c9d6ea',
    'cinematic.sunColor': '#ffffff',
    'cinematic.saturation': 0.18,
  }),

  'outline-dark': Object.freeze({
    'background.color': '#000814',
    'globe.surfaceColor': '#0a1c38',
    // Soft ice-blue borders sit gently above the ocean — readable
    // without screaming "vibrant cyan demo".
    'countries.border.color': '#5b9bcf',
    'countries.border.opacity': 0.7,
    'countries.borderHover.color': '#a5f3fc',
    'countries.borderHover.width': 2,
    'countries.borderHover.glowColor': '#67e8f9',
    'countries.borderHover.glowWidth': 7,
    'countries.borderHover.glowOpacity': 0.55,
    // Warm amber for the pinned country — lone warm note in an
    // otherwise cool palette so a focus instantly stands out.
    'countries.borderActive.color': '#fcd34d',
    'countries.borderActive.width': 2.4,
    // Subtle fill — when the studio enables 'always' mode this
    // produces a barely-perceptible lift over the ocean, just enough
    // to read continent shapes without flatness.
    'countries.fill.defaultColor': '#13294a',
    'countries.fill.opacity': 0.45,
    'countries.label.color': '#9eb8d4',
    'countries.label.fontSize': 11,
    'countries.label.fontWeight': '400',
    // Soft dark halo — keeps labels legible on the lit hemisphere
    // without the loud cyan glow we had before.
    'countries.label.textShadow':
      '0 0 3px rgba(0, 8, 20, 0.85), 0 1px 1px rgba(0, 0, 0, 0.6)',
    'tooltip.backgroundColor': 'rgba(6, 14, 30, 0.92)',
    'tooltip.textColor': '#a5f3fc',
    'lights.ambient.intensity': 0.55,
    'lights.directional.intensity': 0.85,
    'markers.defaultColor': '#fbbf24',
    // Quieter atmosphere — keeps the limb glow but stops it dominating
    // the frame the way intensity 1.7 did.
    'atmosphere.color': '#4a8acc',
    'atmosphere.intensity': 1.15,
    // Starfield slightly less dense + dimmer so it reads as backdrop,
    // not foreground texture.
    'starfield.color': '#dde6f5',
    'starfield.density': 1800,
    'starfield.size': 1.3,
    'arcs.color': '#67e8f9',
    'arcs.headColor': '#fbbf24',
  }),

  'outline-light': Object.freeze({
    'background.color': '#f0f4f8',
    'globe.surfaceColor': '#dde7f0',
    'countries.border.color': '#3870b0',
    'countries.border.opacity': 0.9,
    'countries.borderHover.color': '#1a4880',
    'countries.borderActive.color': '#000000',
    'countries.fill.defaultColor': '#a8c4d8',
    'countries.fill.opacity': 0.58,
    'countries.dotted.color': '#3870b0',
    'countries.dotted.opacity': 0.9,
    'countries.label.color': '#1a1a1a',
    'countries.label.textShadow': '0 0 4px rgba(255, 255, 255, 0.6)',
    'tooltip.backgroundColor': 'rgba(245, 248, 252, 0.95)',
    'tooltip.textColor': '#1a4880',
    'lights.ambient.intensity': 0.7,
    'lights.directional.intensity': 0.9,
    'markers.defaultColor': '#d9534f',
    'atmosphere.color': '#a8c8e8',
    'atmosphere.intensity': 0.8,
    'starfield.color': '#88a0c0',
    'starfield.density': 600,
    'starfield.size': 1.0,
    'arcs.color': '#1a4880',
    'arcs.headColor': '#d9534f',
    'wireframe.color': '#3870b0',
  }),

  'outline-sunset': Object.freeze({
    'background.color': '#1a0820',
    'globe.surfaceColor': '#3a1530',
    'countries.border.color': '#ffb070',
    'countries.borderHover.color': '#ffd166',
    'countries.borderHover.glowColor': '#ff8866',
    'countries.borderHover.glowOpacity': 0.5,
    'countries.borderActive.color': '#ffffff',
    'countries.fill.defaultColor': '#5a2a4f',
    'countries.fill.opacity': 0.4,
    'countries.dotted.color': '#ffd166',
    'tooltip.backgroundColor': 'rgba(40, 20, 30, 0.9)',
    'tooltip.textColor': '#ffd166',
    'markers.defaultColor': '#ff5a5a',
    'atmosphere.color': '#ff8866',
    'atmosphere.intensity': 1.4,
    'starfield.color': '#ffd9aa',
    'starfield.density': 1800,
    'starfield.size': 1.2,
    'arcs.color': '#ffd166',
    'arcs.headColor': '#ff5a5a',
    'wireframe.color': '#ffb070',
  }),

  'outline-cyber': Object.freeze({
    'background.color': '#000010',
    'globe.surfaceColor': '#001a2a',
    'countries.border.color': '#00f0ff',
    'countries.border.width': 1.5,
    'countries.borderHover.color': '#ff00ff',
    'countries.borderHover.width': 2.5,
    'countries.borderHover.glowColor': '#ff00ff',
    'countries.borderHover.glowWidth': 8,
    'countries.borderHover.glowOpacity': 0.55,
    'countries.borderActive.color': '#22ee99',
    'countries.fill.defaultColor': '#001a2a',
    'countries.fill.opacity': 0.5,
    'countries.dotted.color': '#22ee99',
    'countries.dotted.opacity': 1,
    'tooltip.backgroundColor': 'rgba(0, 30, 30, 0.95)',
    'tooltip.textColor': '#22ee99',
    'tooltip.borderRadius': '2px',
    'lights.ambient.intensity': 0.4,
    'lights.directional.intensity': 0.6,
    'markers.defaultColor': '#22ee99',
    'atmosphere.color': '#00f0ff',
    'atmosphere.intensity': 1.6,
    'starfield.color': '#00f0ff',
    'starfield.density': 2000,
    'starfield.size': 1.6,
    'arcs.color': '#ff00ff',
    'arcs.headColor': '#22ee99',
    'wireframe.color': '#00f0ff',
  }),

  'outline-monochrome': Object.freeze({
    'background.color': '#0a0a0a',
    'globe.surfaceColor': '#1a1a1a',
    'countries.border.color': '#cccccc',
    'countries.borderHover.color': '#ffffff',
    'countries.borderHover.width': 2.5,
    'countries.borderHover.glowColor': '#ffffff',
    'countries.borderHover.glowOpacity': 0.35,
    'countries.borderActive.color': '#ffaa00',
    'countries.fill.defaultColor': '#2a2a2a',
    'countries.dotted.color': '#ffffff',
    'countries.dotted.opacity': 0.9,
    'tooltip.backgroundColor': 'rgba(20, 20, 20, 0.9)',
    'tooltip.textColor': '#ffffff',
    'markers.defaultColor': '#ffffff',
    'atmosphere.color': '#888888',
    'atmosphere.intensity': 0.9,
    'starfield.color': '#cccccc',
    'arcs.color': '#ffffff',
    'arcs.headColor': '#ffaa00',
    'wireframe.color': '#cccccc',
  }),

  // Dotted kind — black sphere, glowing cyan dots fill each country.
  'dotted-dark': Object.freeze({
    'background.color': '#000000',
    'globe.surfaceColor': '#000000',
    'countries.border.opacity': 0,
    'countries.fill.defaultColor': '#0a1a2a',
    'countries.fill.opacity': 0.3,
    'countries.dotted.color': '#7fdfff',
    'countries.dotted.size': 0.009,
    'countries.dotted.density': 1.5,
    'countries.dotted.opacity': 0.95,
    'countries.borderHover.color': '#7fdfff',
    'countries.borderActive.color': '#ffffff',
    'tooltip.backgroundColor': 'rgba(0, 8, 16, 0.92)',
    'tooltip.textColor': '#7fdfff',
    'lights.ambient.intensity': 0.4,
    'markers.defaultColor': '#7fdfff',
    'atmosphere.color': '#4a9eff',
    'atmosphere.intensity': 1.6,
    'starfield.color': '#ffffff',
    'starfield.density': 2200,
    'starfield.size': 1.0,
    'arcs.color': '#7fdfff',
    'arcs.headColor': '#ffffff',
  }),

  // Wireframe kind — pure lat/lng grid on black, no countries.
  'wireframe-tron': Object.freeze({
    'background.color': '#000000',
    'globe.surfaceColor': '#000000',
    'countries.border.opacity': 0,
    'countries.fill.opacity': 0,
    'countries.dotted.opacity': 0,
    'countries.borderHover.color': '#22d3ee',
    'countries.borderActive.color': '#ffffff',
    'countries.label.color': '#22d3ee',
    'countries.label.fontFamily': 'JetBrains Mono, ui-monospace, monospace',
    'countries.label.textShadow': '0 0 6px rgba(34, 211, 238, 0.8)',
    'tooltip.backgroundColor': 'rgba(0, 8, 16, 0.9)',
    'tooltip.textColor': '#22d3ee',
    'tooltip.fontFamily': 'JetBrains Mono, ui-monospace, monospace',
    'tooltip.borderRadius': '2px',
    'legend.backgroundColor': 'rgba(0, 8, 16, 0.9)',
    'legend.textColor': '#22d3ee',
    'legend.titleColor': '#ffffff',
    'legend.fontFamily': 'JetBrains Mono, ui-monospace, monospace',
    'legend.borderRadius': '2px',
    'lights.ambient.color': '#22d3ee',
    'lights.ambient.intensity': 0.5,
    'lights.directional.intensity': 0.4,
    'markers.defaultColor': '#22d3ee',
    'atmosphere.color': '#22d3ee',
    'atmosphere.intensity': 1.4,
    'starfield.color': '#22d3ee',
    'starfield.density': 1200,
    'starfield.size': 1.0,
    'arcs.color': '#22d3ee',
    'wireframe.color': '#22d3ee',
    'wireframe.opacity': 0.7,
    'wireframe.density': 1.2,
    'wireframe.pulse': 0.15,
  }),

  // Paper kind — vintage atlas: cream parchment sphere, hand-drawn ink borders.
  'paper-default': Object.freeze({
    'background.color': '#1a1410',
    'globe.surfaceColor': '#d7e2d2',
    'countries.border.color': '#5b3a1f',
    'countries.border.opacity': 0.85,
    'countries.borderHover.color': '#3a2410',
    'countries.borderHover.width': 2,
    'countries.borderHover.glowColor': '#3a2410',
    'countries.borderHover.glowOpacity': 0.25,
    'countries.borderActive.color': '#1a0e05',
    'countries.fill.defaultColor': '#ecd28c',
    'countries.fill.opacity': 0.5,
    'countries.label.color': '#3a2410',
    'countries.label.fontFamily': 'Georgia, "Times New Roman", serif',
    'countries.label.textShadow': '0 0 4px rgba(244, 236, 214, 0.85)',
    'tooltip.backgroundColor': 'rgba(244, 236, 214, 0.92)',
    'tooltip.textColor': '#3a2410',
    'tooltip.fontFamily': 'Georgia, "Times New Roman", serif',
    'legend.backgroundColor': 'rgba(244, 236, 214, 0.92)',
    'legend.textColor': '#3a2410',
    'legend.titleColor': '#1a0e05',
    'legend.fontFamily': 'Georgia, "Times New Roman", serif',
    'lights.ambient.intensity': 0.7,
    'lights.directional.intensity': 0.5,
    'markers.defaultColor': '#a83a25',
    'atmosphere.color': '#a89478',
    'atmosphere.intensity': 0.7,
    'starfield.color': '#bfa974',
    'starfield.density': 400,
    'starfield.size': 0.9,
    'arcs.color': '#5b3a1f',
    'arcs.headColor': '#a83a25',
  }),

  // Hologram kind — semi-transparent turquoise shell with scanlines + Fresnel
  // rim, additive cyan country borders. The outer-glow shell + Fresnel rim
  // already supply the silhouette halo, so we kill the shared atmosphere
  // layer that would otherwise wash everything out. Default-on glitch
  // transients add CRT-style life.
  'hologram-cyan': Object.freeze({
    'background.color': '#020a14',
    'globe.surfaceColor': '#000814',
    'countries.border.opacity': 0,
    'countries.fill.opacity': 0,
    'countries.dotted.opacity': 0,
    'countries.borderHover.color': '#a5f3fc',
    'countries.borderHover.width': 2,
    'countries.borderActive.color': '#ffffff',
    'countries.label.color': '#a5f3fc',
    'countries.label.fontFamily': 'JetBrains Mono, ui-monospace, monospace',
    'countries.label.textShadow': '0 0 6px rgba(103, 232, 249, 0.8)',
    'tooltip.backgroundColor': 'rgba(2, 10, 20, 0.92)',
    'tooltip.textColor': '#67e8f9',
    'tooltip.fontFamily': 'JetBrains Mono, ui-monospace, monospace',
    'tooltip.borderRadius': '2px',
    'legend.backgroundColor': 'rgba(2, 10, 20, 0.92)',
    'legend.textColor': '#67e8f9',
    'legend.titleColor': '#ffffff',
    'legend.fontFamily': 'JetBrains Mono, ui-monospace, monospace',
    'legend.borderRadius': '2px',
    'lights.ambient.color': '#4dd0e1',
    'lights.ambient.intensity': 0.5,
    'lights.directional.intensity': 0.4,
    'markers.defaultColor': '#67e8f9',
    'atmosphere.color': '#4dd0e1',
    'atmosphere.intensity': 0,
    'starfield.color': '#67e8f9',
    'starfield.density': 1800,
    'starfield.size': 1.1,
    'arcs.color': '#67e8f9',
    'arcs.headColor': '#ffffff',
    'hologram.shellOpacity': 0.10,
    'hologram.rimGlow': 1.2,
    'hologram.outerGlowOpacity': 0.08,
    'hologram.borderIntensity': 2.0,
  }),
});
