import type { TokenSet } from './types';

/**
 * Names of built-in theme presets. v0.2.x ships 5 outline-style presets;
 * future plans will add presets for dotted, paper, hologram etc.
 */
export type ThemePresetName =
  | 'outline-dark'
  | 'outline-light'
  | 'outline-sunset'
  | 'outline-cyber'
  | 'outline-monochrome'
  | 'dotted-dark'
  | 'wireframe-tron';

/**
 * Frozen registry of built-in presets. Each preset is a complete TokenSet —
 * `resolveTheme()` uses it as the merge floor when `extends` is set.
 */
export const THEME_PRESETS: Readonly<Record<ThemePresetName, TokenSet>> = Object.freeze({
  'outline-dark': Object.freeze({
    'background.color': '#000010',
    'globe.surfaceColor': '#0b1d3a',
    'globe.surfaceTextureUrl': '',
    'countries.border.color': '#4a9eff',
    'countries.border.width': 1,
    'countries.border.opacity': 0.85,
    'countries.borderHover.color': '#ffd700',
    'countries.borderHover.width': 2,
    'countries.borderHover.opacity': 1,
    'countries.borderActive.color': '#ffffff',
    'countries.borderActive.width': 3,
    'countries.borderActive.opacity': 1,
    'tooltip.backgroundColor': 'rgba(10, 14, 30, 0.85)',
    'tooltip.textColor': '#ffd700',
    'tooltip.fontSize': 12,
    'tooltip.fontFamily': 'system-ui, sans-serif',
    'tooltip.padding': '4px 8px',
    'tooltip.borderRadius': '4px',
    'legend.backgroundColor': 'rgba(10, 14, 30, 0.85)',
    'legend.textColor': '#cfd8e3',
    'legend.titleColor': '#ffffff',
    'legend.fontSize': 11,
    'legend.fontFamily': 'system-ui, sans-serif',
    'legend.padding': '8px 10px',
    'legend.borderRadius': '6px',
    'lights.ambient.color': '#ffffff',
    'lights.ambient.intensity': 0.6,
    'lights.directional.color': '#ffffff',
    'lights.directional.intensity': 0.8,
    'markers.defaultColor': '#ff4444',
    'atmosphere.color': '#4a9eff',
    'atmosphere.intensity': 1.2,
    'starfield.color': '#ffffff',
    'starfield.density': 1500,
    'starfield.size': 1.4,
    'arcs.color': '#ffd700',
    'arcs.width': 1.5,
    'arcs.opacity': 0.9,
    'arcs.headColor': '#ffffff',
    'arcs.headSize': 0.012,
    'countries.fill.defaultColor': '#1a3a6e',
    'countries.fill.opacity': 0.4,
    'countries.dotted.color': '#7fdfff',
    'countries.dotted.size': 0.008,
    'countries.dotted.density': 1.5,
    'countries.dotted.opacity': 0.95,
    'countries.label.color': '#ffffff',
    'countries.label.fontSize': 11,
    'countries.label.fontFamily': 'system-ui, sans-serif',
    'countries.label.fontWeight': '500',
    'countries.label.textShadow': '0 0 4px rgba(0, 0, 0, 0.7)',
    'wireframe.color': '#22d3ee',
    'wireframe.opacity': 0,
    'wireframe.density': 1,
    'wireframe.pulse': 0,
  }),
  'outline-light': Object.freeze({
    'background.color': '#f0f4f8',
    'globe.surfaceColor': '#dde7f0',
    'globe.surfaceTextureUrl': '',
    'countries.border.color': '#3870b0',
    'countries.border.width': 1,
    'countries.border.opacity': 0.9,
    'countries.borderHover.color': '#1a4880',
    'countries.borderHover.width': 2,
    'countries.borderHover.opacity': 1,
    'countries.borderActive.color': '#000000',
    'countries.borderActive.width': 3,
    'countries.borderActive.opacity': 1,
    'tooltip.backgroundColor': 'rgba(245, 248, 252, 0.95)',
    'tooltip.textColor': '#1a4880',
    'tooltip.fontSize': 12,
    'tooltip.fontFamily': 'system-ui, sans-serif',
    'tooltip.padding': '4px 8px',
    'tooltip.borderRadius': '4px',
    'legend.backgroundColor': 'rgba(10, 14, 30, 0.85)',
    'legend.textColor': '#cfd8e3',
    'legend.titleColor': '#ffffff',
    'legend.fontSize': 11,
    'legend.fontFamily': 'system-ui, sans-serif',
    'legend.padding': '8px 10px',
    'legend.borderRadius': '6px',
    'lights.ambient.color': '#ffffff',
    'lights.ambient.intensity': 0.7,
    'lights.directional.color': '#ffffff',
    'lights.directional.intensity': 0.9,
    'markers.defaultColor': '#d9534f',
    'atmosphere.color': '#a8c8e8',
    'atmosphere.intensity': 0.8,
    'starfield.color': '#88a0c0',
    'starfield.density': 600,
    'starfield.size': 1.0,
    'arcs.color': '#1a4880',
    'arcs.width': 1.5,
    'arcs.opacity': 0.9,
    'arcs.headColor': '#d9534f',
    'arcs.headSize': 0.012,
    'countries.fill.defaultColor': '#a8c4d8',
    'countries.fill.opacity': 0.5,
    'countries.dotted.color': '#3870b0',
    'countries.dotted.size': 0.008,
    'countries.dotted.density': 1.5,
    'countries.dotted.opacity': 0.9,
    'countries.label.color': '#1a1a1a',
    'countries.label.fontSize': 11,
    'countries.label.fontFamily': 'system-ui, sans-serif',
    'countries.label.fontWeight': '500',
    'countries.label.textShadow': '0 0 4px rgba(255, 255, 255, 0.6)',
    'wireframe.color': '#3870b0',
    'wireframe.opacity': 0,
    'wireframe.density': 1,
    'wireframe.pulse': 0,
  }),
  'outline-sunset': Object.freeze({
    'background.color': '#180a1a',
    'globe.surfaceColor': '#3a1f3f',
    'globe.surfaceTextureUrl': '',
    'countries.border.color': '#ffb070',
    'countries.border.width': 1,
    'countries.border.opacity': 0.85,
    'countries.borderHover.color': '#ffe9a0',
    'countries.borderHover.width': 2,
    'countries.borderHover.opacity': 1,
    'countries.borderActive.color': '#ffffff',
    'countries.borderActive.width': 3,
    'countries.borderActive.opacity': 1,
    'tooltip.backgroundColor': 'rgba(40, 14, 30, 0.85)',
    'tooltip.textColor': '#ffe9a0',
    'tooltip.fontSize': 12,
    'tooltip.fontFamily': 'system-ui, sans-serif',
    'tooltip.padding': '4px 8px',
    'tooltip.borderRadius': '4px',
    'legend.backgroundColor': 'rgba(10, 14, 30, 0.85)',
    'legend.textColor': '#cfd8e3',
    'legend.titleColor': '#ffffff',
    'legend.fontSize': 11,
    'legend.fontFamily': 'system-ui, sans-serif',
    'legend.padding': '8px 10px',
    'legend.borderRadius': '6px',
    'lights.ambient.color': '#ffe0d0',
    'lights.ambient.intensity': 0.7,
    'lights.directional.color': '#ffaa80',
    'lights.directional.intensity': 0.9,
    'markers.defaultColor': '#ffd166',
    'atmosphere.color': '#ff7e5f',
    'atmosphere.intensity': 1.6,
    'starfield.color': '#fff0c8',
    'starfield.density': 1800,
    'starfield.size': 1.6,
    'arcs.color': '#ffe9a0',
    'arcs.width': 1.5,
    'arcs.opacity': 0.9,
    'arcs.headColor': '#ffd166',
    'arcs.headSize': 0.012,
    'countries.fill.defaultColor': '#5a2a4f',
    'countries.fill.opacity': 0.4,
    'countries.dotted.color': '#ffd166',
    'countries.dotted.size': 0.008,
    'countries.dotted.density': 1.5,
    'countries.dotted.opacity': 0.95,
    'countries.label.color': '#ffffff',
    'countries.label.fontSize': 11,
    'countries.label.fontFamily': 'system-ui, sans-serif',
    'countries.label.fontWeight': '500',
    'countries.label.textShadow': '0 0 4px rgba(0, 0, 0, 0.7)',
    'wireframe.color': '#ffb070',
    'wireframe.opacity': 0,
    'wireframe.density': 1,
    'wireframe.pulse': 0,
  }),
  'outline-cyber': Object.freeze({
    'background.color': '#000814',
    'globe.surfaceColor': '#0a0a14',
    'globe.surfaceTextureUrl': '',
    'countries.border.color': '#00f0ff',
    'countries.border.width': 1,
    'countries.border.opacity': 1,
    'countries.borderHover.color': '#ff2bd6',
    'countries.borderHover.width': 2,
    'countries.borderHover.opacity': 1,
    'countries.borderActive.color': '#ffffff',
    'countries.borderActive.width': 3,
    'countries.borderActive.opacity': 1,
    'tooltip.backgroundColor': 'rgba(0, 8, 20, 0.85)',
    'tooltip.textColor': '#22ee99',
    'tooltip.fontSize': 12,
    'tooltip.fontFamily': 'JetBrains Mono, monospace',
    'tooltip.padding': '4px 8px',
    'tooltip.borderRadius': '2px',
    'legend.backgroundColor': 'rgba(10, 14, 30, 0.85)',
    'legend.textColor': '#cfd8e3',
    'legend.titleColor': '#ffffff',
    'legend.fontSize': 11,
    'legend.fontFamily': 'system-ui, sans-serif',
    'legend.padding': '8px 10px',
    'legend.borderRadius': '6px',
    'lights.ambient.color': '#88ccff',
    'lights.ambient.intensity': 0.5,
    'lights.directional.color': '#ffffff',
    'lights.directional.intensity': 0.6,
    'markers.defaultColor': '#22ee99',
    'atmosphere.color': '#ff2bd6',
    'atmosphere.intensity': 1.4,
    'starfield.color': '#88f0ff',
    'starfield.density': 2200,
    'starfield.size': 1.2,
    'arcs.color': '#22ee99',
    'arcs.width': 1.5,
    'arcs.opacity': 0.9,
    'arcs.headColor': '#ff2bd6',
    'arcs.headSize': 0.012,
    'countries.fill.defaultColor': '#001a2a',
    'countries.fill.opacity': 0.5,
    'countries.dotted.color': '#22ee99',
    'countries.dotted.size': 0.008,
    'countries.dotted.density': 1.5,
    'countries.dotted.opacity': 1,
    'countries.label.color': '#1a1a1a',
    'countries.label.fontSize': 11,
    'countries.label.fontFamily': 'system-ui, sans-serif',
    'countries.label.fontWeight': '500',
    'countries.label.textShadow': '0 0 4px rgba(255, 255, 255, 0.6)',
    'wireframe.color': '#00f0ff',
    'wireframe.opacity': 0,
    'wireframe.density': 1,
    'wireframe.pulse': 0,
  }),
  'outline-monochrome': Object.freeze({
    'background.color': '#0a0a0a',
    'globe.surfaceColor': '#1a1a1a',
    'globe.surfaceTextureUrl': '',
    'countries.border.color': '#cccccc',
    'countries.border.width': 1,
    'countries.border.opacity': 0.85,
    'countries.borderHover.color': '#ffffff',
    'countries.borderHover.width': 2.5,
    'countries.borderHover.opacity': 1,
    'countries.borderActive.color': '#ffaa00',
    'countries.borderActive.width': 3,
    'countries.borderActive.opacity': 1,
    'tooltip.backgroundColor': 'rgba(20, 20, 20, 0.9)',
    'tooltip.textColor': '#ffffff',
    'tooltip.fontSize': 12,
    'tooltip.fontFamily': 'system-ui, sans-serif',
    'tooltip.padding': '4px 8px',
    'tooltip.borderRadius': '4px',
    'legend.backgroundColor': 'rgba(10, 14, 30, 0.85)',
    'legend.textColor': '#cfd8e3',
    'legend.titleColor': '#ffffff',
    'legend.fontSize': 11,
    'legend.fontFamily': 'system-ui, sans-serif',
    'legend.padding': '8px 10px',
    'legend.borderRadius': '6px',
    'lights.ambient.color': '#ffffff',
    'lights.ambient.intensity': 0.6,
    'lights.directional.color': '#ffffff',
    'lights.directional.intensity': 0.8,
    'markers.defaultColor': '#ffffff',
    'atmosphere.color': '#888888',
    'atmosphere.intensity': 0.9,
    'starfield.color': '#cccccc',
    'starfield.density': 1500,
    'starfield.size': 1.4,
    'arcs.color': '#ffffff',
    'arcs.width': 1.5,
    'arcs.opacity': 0.9,
    'arcs.headColor': '#ffaa00',
    'arcs.headSize': 0.012,
    'countries.fill.defaultColor': '#2a2a2a',
    'countries.fill.opacity': 0.4,
    'countries.dotted.color': '#ffffff',
    'countries.dotted.size': 0.008,
    'countries.dotted.density': 1.5,
    'countries.dotted.opacity': 0.9,
    'countries.label.color': '#ffffff',
    'countries.label.fontSize': 11,
    'countries.label.fontFamily': 'system-ui, sans-serif',
    'countries.label.fontWeight': '500',
    'countries.label.textShadow': '0 0 4px rgba(0, 0, 0, 0.7)',
    'wireframe.color': '#cccccc',
    'wireframe.opacity': 0,
    'wireframe.density': 1,
    'wireframe.pulse': 0,
  }),
  'dotted-dark': Object.freeze({
    'background.color': '#000000',
    'globe.surfaceColor': '#000000',
    'globe.surfaceTextureUrl': '',
    'countries.border.color': '#7fdfff',
    'countries.border.width': 1,
    'countries.border.opacity': 0,
    'countries.borderHover.color': '#ffffff',
    'countries.borderHover.width': 2,
    'countries.borderHover.opacity': 0.9,
    'countries.borderActive.color': '#ffffff',
    'countries.borderActive.width': 2.5,
    'countries.borderActive.opacity': 1,
    'tooltip.backgroundColor': 'rgba(0, 0, 0, 0.9)',
    'tooltip.textColor': '#7fdfff',
    'tooltip.fontSize': 12,
    'tooltip.fontFamily': 'system-ui, sans-serif',
    'tooltip.padding': '4px 8px',
    'tooltip.borderRadius': '4px',
    'legend.backgroundColor': 'rgba(0, 0, 0, 0.85)',
    'legend.textColor': '#cfd8e3',
    'legend.titleColor': '#ffffff',
    'legend.fontSize': 11,
    'legend.fontFamily': 'system-ui, sans-serif',
    'legend.padding': '8px 10px',
    'legend.borderRadius': '6px',
    'lights.ambient.color': '#ffffff',
    'lights.ambient.intensity': 0.6,
    'lights.directional.color': '#ffffff',
    'lights.directional.intensity': 0.6,
    'markers.defaultColor': '#7fdfff',
    'atmosphere.color': '#4a9eff',
    'atmosphere.intensity': 1.4,
    'starfield.color': '#ffffff',
    'starfield.density': 1800,
    'starfield.size': 1.2,
    'arcs.color': '#7fdfff',
    'arcs.width': 1.5,
    'arcs.opacity': 0.9,
    'arcs.headColor': '#ffffff',
    'arcs.headSize': 0.012,
    'countries.fill.defaultColor': '#0a1a2a',
    'countries.fill.opacity': 0.3,
    'countries.dotted.color': '#7fdfff',
    'countries.dotted.size': 0.009,
    'countries.dotted.density': 1.5,
    'countries.dotted.opacity': 0.95,
    'countries.label.color': '#ffffff',
    'countries.label.fontSize': 11,
    'countries.label.fontFamily': 'system-ui, sans-serif',
    'countries.label.fontWeight': '500',
    'countries.label.textShadow': '0 0 4px rgba(0, 0, 0, 0.7)',
    'wireframe.color': '#cccccc',
    'wireframe.opacity': 0,
    'wireframe.density': 1,
    'wireframe.pulse': 0,
  }),
  'wireframe-tron': Object.freeze({
    'background.color': '#000000',
    'globe.surfaceColor': '#000000',
    'globe.surfaceTextureUrl': '',
    'countries.border.color': '#22d3ee',
    'countries.border.width': 1,
    'countries.border.opacity': 0,
    'countries.borderHover.color': '#ffffff',
    'countries.borderHover.width': 2,
    'countries.borderHover.opacity': 1,
    'countries.borderActive.color': '#ffffff',
    'countries.borderActive.width': 3,
    'countries.borderActive.opacity': 1,
    'countries.fill.defaultColor': '#001018',
    'countries.fill.opacity': 0,
    'countries.dotted.color': '#22d3ee',
    'countries.dotted.size': 0.008,
    'countries.dotted.density': 1.5,
    'countries.dotted.opacity': 0,
    'countries.label.color': '#22d3ee',
    'countries.label.fontSize': 11,
    'countries.label.fontFamily': 'JetBrains Mono, ui-monospace, monospace',
    'countries.label.fontWeight': '500',
    'countries.label.textShadow': '0 0 6px rgba(34, 211, 238, 0.8)',
    'tooltip.backgroundColor': 'rgba(0, 8, 16, 0.9)',
    'tooltip.textColor': '#22d3ee',
    'tooltip.fontSize': 12,
    'tooltip.fontFamily': 'JetBrains Mono, ui-monospace, monospace',
    'tooltip.padding': '4px 8px',
    'tooltip.borderRadius': '2px',
    'legend.backgroundColor': 'rgba(0, 8, 16, 0.9)',
    'legend.textColor': '#22d3ee',
    'legend.titleColor': '#ffffff',
    'legend.fontSize': 11,
    'legend.fontFamily': 'JetBrains Mono, ui-monospace, monospace',
    'legend.padding': '8px 10px',
    'legend.borderRadius': '2px',
    'lights.ambient.color': '#22d3ee',
    'lights.ambient.intensity': 0.5,
    'lights.directional.color': '#ffffff',
    'lights.directional.intensity': 0.4,
    'markers.defaultColor': '#22d3ee',
    'atmosphere.color': '#22d3ee',
    'atmosphere.intensity': 1.4,
    'starfield.color': '#22d3ee',
    'starfield.density': 1200,
    'starfield.size': 1.0,
    'arcs.color': '#22d3ee',
    'arcs.width': 1.5,
    'arcs.opacity': 0.9,
    'arcs.headColor': '#ffffff',
    'arcs.headSize': 0.012,
    'wireframe.color': '#22d3ee',
    'wireframe.opacity': 0.7,
    'wireframe.density': 1.2,
    'wireframe.pulse': 0.15,
  }),
});
