import type { TokenSet } from './types';

/**
 * Built-in default tokens. Used as the merge floor by `resolveTheme()`.
 * Values mirror the original hardcoded defaults from globe.ts.
 */
export const DEFAULT_TOKENS: TokenSet = Object.freeze({
  'background.color': '#000010',
  'globe.surfaceColor': '#0b1d3a',
  'globe.surfaceTextureUrl': '',
  'countries.border.color': '#4a9eff',
  'countries.border.width': 1,
  'countries.border.opacity': 0.85,
  'countries.borderHover.color': '#ffd700',
  'countries.borderHover.width': 2,
  'countries.borderHover.opacity': 1,
  'countries.borderActive.color': '#ffffff',
  'countries.borderActive.width': 3,
  'countries.borderActive.opacity': 1,
  'countries.fill.defaultColor': '#1a3a6e',
  'countries.fill.opacity': 0.4,
  'tooltip.backgroundColor': 'rgba(10, 14, 30, 0.85)',
  'tooltip.textColor': '#ffd700',
  'tooltip.fontSize': 12,
  'tooltip.fontFamily': 'system-ui, sans-serif',
  'tooltip.padding': '4px 8px',
  'tooltip.borderRadius': '4px',
  'legend.backgroundColor': 'rgba(10, 14, 30, 0.85)',
  'legend.textColor': '#cfd8e3',
  'legend.titleColor': '#ffffff',
  'legend.fontSize': 11,
  'legend.fontFamily': 'system-ui, sans-serif',
  'legend.padding': '8px 10px',
  'legend.borderRadius': '6px',
  'lights.ambient.color': '#ffffff',
  'lights.ambient.intensity': 0.6,
  'lights.directional.color': '#ffffff',
  'lights.directional.intensity': 0.8,
  'markers.defaultColor': '#ff4444',
  'atmosphere.color': '#4a9eff',
  'atmosphere.intensity': 1.2,
  'starfield.color': '#ffffff',
  'starfield.density': 1500,
  'starfield.size': 1.4,
  'arcs.color': '#ffd700',
  'arcs.width': 1.5,
  'arcs.opacity': 0.9,
  'arcs.headColor': '#ffffff',
  'arcs.headSize': 0.012,
});
