import type { TokenSet } from './types';

/**
 * Built-in default tokens. Used as the merge floor by `resolveTheme()`.
 * Values mirror the original hardcoded defaults from globe.ts.
 */
export const DEFAULT_TOKENS: TokenSet = Object.freeze({
  'background.color': '#000010',
  'globe.surfaceColor': '#0b1d3a',
  'globe.surfaceTextureUrl': '',
  'countries.border.color': '#4a9eff',
  'countries.border.width': 1,
  'countries.border.opacity': 0.85,
  'countries.borderHover.color': '#ffd700',
  'countries.borderHover.width': 2,
  'countries.borderHover.opacity': 1,
  'countries.borderHover.glowColor': '#ffd700',
  'countries.borderHover.glowWidth': 6,
  'countries.borderHover.glowOpacity': 0.45,
  'countries.borderActive.color': '#ffffff',
  'countries.borderActive.width': 3,
  'countries.borderActive.opacity': 1,
  'countries.fill.defaultColor': '#1a3a6e',
  'countries.fill.opacity': 0.4,
  'countries.dotted.color': '#7fdfff',
  'countries.dotted.size': 0.008,
  'countries.dotted.density': 1.5,
  'countries.dotted.opacity': 0.95,
  'countries.dotted.rippleBoost': 1.5,
  'countries.dotted.rippleSpeed': 1.2,
  'countries.dotted.rippleWidth': 0.18,
  'countries.dotted.flashColor': '#ffffff',
  'countries.dotted.flashStrength': 2.0,
  'countries.dotted.flashDecay': 4,
  'countries.dotted.driftAmplitude': 0.15,
  'countries.dotted.driftSpeed': 0.4,
  'countries.dotted.driftFreq': 3.0,
  'countries.dotted.driftAxis': 'ns',
  'countries.dotted.hoverScale': 1.3,
  'countries.dotted.hoverBrightnessBoost': 0.7,
  'countries.dotted.hoverDuration': 0.25,
  'countries.label.color': '#ffffff',
  'countries.label.fontSize': 11,
  'countries.label.fontFamily': 'system-ui, sans-serif',
  'countries.label.fontWeight': '500',
  'countries.label.textShadow': '0 0 4px rgba(0, 0, 0, 0.7)',
  'tooltip.backgroundColor': 'rgba(10, 14, 30, 0.85)',
  'tooltip.textColor': '#ffd700',
  'tooltip.fontSize': 12,
  'tooltip.fontFamily': 'system-ui, sans-serif',
  'tooltip.padding': '4px 8px',
  'tooltip.borderRadius': '4px',
  'legend.backgroundColor': 'rgba(10, 14, 30, 0.85)',
  'legend.textColor': '#cfd8e3',
  'legend.titleColor': '#ffffff',
  'legend.fontSize': 11,
  'legend.fontFamily': 'system-ui, sans-serif',
  'legend.padding': '8px 10px',
  'legend.borderRadius': '6px',
  'lights.ambient.color': '#ffffff',
  'lights.ambient.intensity': 0.6,
  'lights.directional.color': '#ffffff',
  'lights.directional.intensity': 0.8,
  'markers.defaultColor': '#ff4444',
  'atmosphere.color': '#4a9eff',
  'atmosphere.intensity': 1.2,
  'starfield.color': '#ffffff',
  'starfield.density': 1500,
  'starfield.size': 1.4,
  'arcs.color': '#ffd700',
  'arcs.width': 1.5,
  'arcs.opacity': 0.9,
  'arcs.headColor': '#ffffff',
  'arcs.headSize': 0.012,
  'wireframe.color': '#22d3ee',
  'wireframe.opacity': 0.55,
  'wireframe.density': 1,
  'wireframe.pulse': 0,
  'wireframe.pulseColor': '#22d3ee',
  'wireframe.pulseSpeed': 1.5,
  'wireframe.pulseWidth': 0.18,
  'wireframe.pulseBoost': 2.5,
  'wireframe.equatorColor': '#7ff0ff',
  'wireframe.equatorOpacity': 0.85,
  'wireframe.emphasisEnabled': true,
  'wireframe.glitchEnabled': true,
  'wireframe.glitchIntervalMin': 5,
  'wireframe.glitchIntervalMax': 15,
  'wireframe.activeRingColor': '#22d3ee',
  'wireframe.activeRingOpacity': 0.7,
  'wireframe.activeRingThickness': 0.015,
  'wireframe.activeRingRotationSpeed': 0.5,
  'wireframe.activeRingPadding': 1.2,
  'wireframe.streamColor': '#67e8f9',
  'wireframe.streamCount': 16,
  'wireframe.streamSize': 0.012,
  'wireframe.streamSpeed': 0.6,
  'wireframe.streamOpacity': 0.85,
  'paper.surfaceColor': '#d7e2d2',
  'paper.surfaceNoiseAmount': 0.06,
  'paper.borderColor': '#5b3a1f',
  'paper.borderOpacity': 0.85,
  'paper.borderRoughness': 0.12,
  'paper.fillColor': '#ecd28c',
  'paper.fillOpacity': 0.78,
  'paper.gridColor': '#bfa974',
  'paper.gridOpacity': 0.18,
  'hologram.color': '#4dd0e1',
  'hologram.shellOpacity': 0.18,
  'hologram.rimGlow': 1.4,
  'hologram.scanlineFreq': 240,
  'hologram.scanlineSpeed': 1.5,
  'hologram.borderColor': '#67e8f9',
  'hologram.borderIntensity': 1.6,
  'hologram.glitchAmount': 0.025,
  'hologram.glitchIntervalMin': 4,
  'hologram.glitchIntervalMax': 9,
  'hologram.outerGlowOpacity': 0.12,
  'cinematic.oceanColor': '#02121f',
  'cinematic.landColor': '#7d552e',
  'cinematic.cloudColor': '#c9eeff',
  'cinematic.nightColor': '#020612',
  'cinematic.lightDirectionX': -0.45,
  'cinematic.lightDirectionY': 0.66,
  'cinematic.lightDirectionZ': 0.58,
  'cinematic.terminatorSoftness': 0.38,
  'cinematic.terminatorContrast': 1.38,
  'cinematic.keyIntensity': 1.34,
  'cinematic.fillIntensity': 0.16,
  'cinematic.rimColor': '#b9ecff',
  'cinematic.rimIntensity': 0.72,
  'cinematic.rimPower': 2.78,
  'cinematic.specularIntensity': 0.76,
  'cinematic.cityLightColor': '#ffd36a',
  'cinematic.cityLightIntensity': 1.08,
  'cinematic.networkColor': '#f7b84d',
  'cinematic.networkOpacity': 0.34,
  'cinematic.borderColor': '#f6b44d',
  'cinematic.borderIntensity': 0.94,
});
