import type { FeatureDoc } from './types';
import { COUNTRY_DATA, MARKERS } from '../snippets';

export const DATA_FEATURES: ReadonlyArray<FeatureDoc> = [
  {
    id: 'country-data',
    title: 'Country data',
    configPaths: ['countryData'],
    methods: ['setCountryData', 'getCountryData'],
    summary: 'Colour countries from a map keyed by ISO id: an explicit colour and opacity per country, or a value mapped through a scale.',
    kinds: ['outline', 'dotted', 'paper', 'cinematic', 'hologram'],
    docs: { slug: 'data/country-data' },
    example: COUNTRY_DATA,
    related: ['scales', 'legend', 'country-fill', 'country-ids'],
  },
  {
    id: 'scales',
    title: 'Colour scales',
    summary: 'Sequential, diverging, threshold and categorical scales with twelve built-in palettes or your own stops. Shared by every data layer.',
    kinds: 'all',
    docs: { slug: 'data/legends', anchor: 'scales' },
    related: ['country-data', 'legend', 'data-layers'],
  },
  {
    id: 'legend',
    title: 'Legend',
    methods: ['showLegend', 'hideLegend'],
    summary: 'A DOM legend pinned to a corner of the globe container, rendered from a scale: gradient bar with ticks or a swatch list.',
    kinds: 'all',
    docs: { slug: 'data/legends', anchor: 'legend' },
    related: ['scales'],
  },
  {
    id: 'markers',
    title: 'Markers',
    configPaths: ['markers'],
    methods: ['setMarkers', 'addMarker', 'removeMarker'],
    events: ['markerClick', 'markerHover'],
    summary: 'Instanced pins at coordinates with colour, size, label, a payload and an optional pulse. Thousands cost nothing; hover scales them up.',
    kinds: 'all',
    docs: { slug: 'data/markers' },
    example: MARKERS,
    related: ['html-markers', 'arcs'],
  },
  {
    id: 'html-markers',
    title: 'HTML markers',
    configPaths: ['htmlMarkers'],
    methods: ['setHtmlMarkers', 'addHtmlMarker', 'removeHtmlMarker'],
    summary: 'Your own DOM element anchored to a coordinate, repositioned every frame, with anchor, offset, occlusion fade and click-through.',
    kinds: 'all',
    docs: { slug: 'data/markers', anchor: 'html-markers' },
    related: ['markers', 'projection'],
  },
  {
    id: 'arcs',
    title: 'Arcs',
    configPaths: ['arcs'],
    methods: ['setArcs', 'addArc', 'removeArc'],
    summary: 'Great-circle connections lifted off the surface: fixed or distance-based height, solid or dashed, with an animated head particle.',
    kinds: 'all',
    docs: { slug: 'data/arcs' },
    related: ['markers'],
  },
  {
    id: 'country-labels',
    title: 'Country labels',
    configPaths: ['countryLabels'],
    methods: ['setCountryLabelsEnabled', 'setCountryLabels'],
    summary: 'HTML name labels at each country centroid with zoom-based fading, occlusion, halo and per-id overrides.',
    kinds: 'all',
    docs: { slug: 'data/labels' },
    related: ['country-data', 'html-markers'],
  },
  {
    id: 'data-layers',
    title: 'Data layers',
    methods: ['setDataLayer', 'getDataLayer', 'playDataLayerAnimation'],
    summary: 'One high-level visualisation at a time on top of any kind: choropleth, bars, extruded countries, heatmap, hex bins or anchored charts.',
    kinds: 'all',
    docs: { slug: 'data/data-layers' },
    related: ['country-data', 'scales'],
  },
  {
    id: 'cinematic-data',
    title: 'Cinematic dataset',
    methods: ['setCinematicData', 'getCinematicData'],
    summary: 'City lights and a route network baked into the cinematic surface. Independent of the data-layer slot, so both can be active.',
    kinds: ['cinematic'],
    docs: { slug: 'kinds/cinematic', anchor: 'dataset' },
    related: ['kind-cinematic', 'data-layers'],
  },
];
