import type {
  ActiveLayer,
  ConfiguratorState,
  GlobeSettings,
  HeatmapSettings,
  HeatmapSurfaceMode,
} from './types';

export const defaultGlobeSettings: GlobeSettings = {
  kind: 'outline',
  theme: 'outline-dark',
  countryResolution: 'low',
  hoverEnabled: true,
  hoverOccludeBackSide: true,
  countryLabels: false,
  labelMinScreenSize: 72,
  labelSizeFadeRange: 0.4,
  labelTransitionMs: 200,
  labelHaloEnabled: false,
  labelHaloRadius: 2,
  labelHaloColor: '#000000',
  labelHaloSteps: 6,
  labelColor: '',
  labelFontSize: 12,
  labelFontWeight: '500',
  autoRotate: true,
  autoRotateSpeed: 0.08,
  axisTilt: 23.5,
  atmosphere: true,
  atmosphereColor: '',
  atmosphereIntensity: 0,
  atmosphereRadiusScale: 0,
  atmospherePower: 0,
  atmosphereThreshold: 0.6,
  atmosphereSide: 'back',
  atmosphereBlending: 'additive',
  atmospherePulse: false,
  atmospherePulseSpeed: 0.25,
  atmospherePulseAmplitude: 0.25,
  starfield: true,
  starfieldDensity: 1500,
  starfieldSize: 1.4,
  starfieldSizeVariety: 0.5,
  starfieldMultiColor: true,
  starfieldPalette: ['#ffffff', '#fff4d6', '#ffe4b3', '#cfdcff', '#b9c8ff'],
  starfieldTwinkle: true,
  starfieldTwinkleIntensity: 0.45,
  starfieldTwinkleSpeed: 0.55,
  focusPulse: true,
  focusPulseOrigin: 'click',
  focusPulseOnSurfaceClick: true,
  outlinePulseDurationMs: 1400,
  outlinePulseRadiusBase: 0.06,
  outlinePulseAngularBand: 0.013,
  outlinePulseScaleMin: 0.4,
  outlinePulseScaleMax: 2.5,
  outlinePulseOpacity: 1,
  outlinePulseSegments: 96,
  outlinePulseColor: '',
  outlinePulseRadiusFactor: 1.0045,
  outlineHoverLift: 0,
  outlineHoverGlowLift: 0.0035,
  outlineHoverGlowEnabled: true,
  outlineContinentDim: false,
  outlineContinentDimAmount: 0.4,
  outlineHoverCrosshair: true,
  outlineHoverCrosshairColor: '',
  outlineHoverCrosshairSize: 0.012,
  outlineHoverCrosshairOpacity: 0.85,
  outlineHoverCrosshairRingRadiusFactor: 0.7,
  outlineHoverCrosshairCardinalTicks: true,
  outlineHoverCrosshairTooltip: true,
  outlineHoverCrosshairTooltipDecimals: 2,
  // Dotted defaults — empty-string colors / 0 numerics mean "use theme
  // default" sentinel; sensible booleans default-on so the workshop's
  // baseline preview shows the dot field at full personality.
  dottedColor: '',
  dottedSizeScale: 1,
  dottedOpacity: 0,
  dottedRipple: true,
  dottedRippleBoost: 1.5,
  dottedRippleSpeed: 1.2,
  dottedRippleWidth: 0.18,
  dottedRippleMaxConcurrent: 3,
  dottedRippleColor: '',
  dottedFlash: true,
  dottedFlashStrength: 2,
  dottedFlashDecay: 4,
  dottedFlashColor: '',
  dottedDrift: true,
  dottedDriftAmplitude: 0.15,
  dottedDriftSpeed: 0.4,
  dottedDriftFreq: 3,
  dottedDriftAxis: 'ns',
  dottedDriftPerCountryPhase: true,
  dottedHoverDots: true,
  dottedHoverScale: 1.3,
  dottedHoverBrightnessBoost: 0.7,
  dottedHoverDuration: 0.25,
  dottedCursorWake: true,
  dottedCursorWakeAmplitude: 0.6,
  dottedCursorWakeFade: 0.45,
  dottedCursorWakeWidth: 0.09,
  dottedLatitudeBands: false,
  dottedEquatorBoost: 0.35,
  dottedTropicsBoost: 0.18,
  dottedLatitudeBandWidth: 4,
  dottedPulseBreath: false,
  dottedPulseBreathAmplitude: 0.12,
  dottedPulseBreathSpeed: 0.35,
  dottedConstellation: false,
  dottedConstellationColor: '',
  dottedConstellationOpacity: 0.55,
  dottedConstellationDistanceFactor: 1.6,
  // Hover lift defaults to a subtle ~0.8% radial bump; bigger reads as
  // a cinematic country pop-out.
  dottedHoverLift: 0.008,
  // Pinned-country pulse default-on so the workshop's preview shows
  // the visual the moment the user clicks a country to pin it.
  dottedActiveCountry: true,
  dottedActiveBoost: 0.65,
  dottedActiveScale: 1.18,
  dottedActivePulseSpeed: 0.65,
  dottedActiveLift: 0.012,
  // Border dots default-on — the dotted analogue of the standard
  // country highlight stroke that dotted opted out of.
  dottedBorderDots: true,
  dottedBorderDotsColor: '',
  dottedBorderDotsSize: 5.5,
  dottedBorderDotsOpacity: 1,
  // Hologram defaults — picked to match the existing tokens' look so the
  // user opens the preset and sees the same projection they'd get with a
  // bare `kind: 'hologram'`. Every numeric default-of-0 = "use theme
  // default" sentinel that the core layer interprets as "leave alone".
  hologramScanlines: true,
  hologramScanlineSpeed: 0,
  hologramScanlineDensity: 0,
  hologramScanlineOpacity: 0.4,
  hologramScanlineDirection: 'horizontal',
  hologramRimGlow: true,
  hologramRimColor: '',
  hologramRimIntensity: 0,
  hologramRimWidth: 2,
  hologramGlitch: true,
  hologramGlitchIntervalMin: 4,
  hologramGlitchIntervalMax: 9,
  hologramGlitchAmplitude: 0,
  hologramGlitchChannelShift: 0.5,
  hologramOuterGlow: true,
  hologramOuterGlowColor: '',
  hologramOuterGlowSpread: 1.02,
  hologramOuterGlowIntensity: 0,
  hologramChromaticAberration: true,
  hologramChromaticAberrationAmount: 0.45,
  hologramChromaticAberrationMode: 'rim',
  hologramNoise: true,
  hologramNoiseIntensity: 0.18,
  hologramNoiseScale: 1.6,
  hologramNoiseSpeed: 22,
  hologramProjectorPulse: true,
  hologramProjectorPulseSpeed: 0.35,
  hologramProjectorPulseAmplitude: 0.6,
  hologramProjectorPulseColor: '',
  hologramDataScan: true,
  hologramDataScanSpeed: 0.2,
  hologramDataScanWidth: 0.05,
  hologramDataScanOpacity: 0.7,
  hologramDataScanAxis: 'horizontal',
  hologramDataScanColor: '',
  hologramPhaseShimmer: false,
  hologramPhaseShimmerScale: 60,
  hologramPhaseShimmerIntensity: 0.12,
  hologramPhaseShimmerSpeed: 0.4,
  hologramCalibrationTicks: false,
  hologramCalibrationTicksCount: 36,
  hologramCalibrationTicksLength: 0.04,
  hologramCalibrationTicksOpacity: 0.9,
  // Paper kind defaults — chosen so every effect off → identical to the
  // pre-redesign "minimal" paper. Knobs can dial each one to taste.
  paperSurfaceColor: '',
  paperSurfaceNoise: -1,
  paperSurfaceVignette: 0.18,
  paperBorders: true,
  paperBorderColor: '',
  paperBorderOpacity: -1,
  paperBorderWidth: 1,
  paperBorderRoughness: 0.25,
  paperStipple: false,
  paperStippleDensity: 1.5,
  paperStippleSize: 1,
  paperInkBleed: true,
  paperInkBleedColor: '',
  paperInkBleedOpacity: 0.3,
  paperInkBleedSpread: 0.0008,
  paperFill: true,
  paperFillColor: '',
  paperFillOpacity: -1,
  paperFillMode: 'single',
  paperGrid: true,
  paperGridColor: '',
  paperGridOpacity: -1,
  paperGridStep: 15,
  paperGridMajorEvery: 3,
  paperGridMajorOpacity: -1,
  paperSepia: false,
  paperSepiaColor: '#8b6f47',
  paperSepiaOpacity: 0.18,
  paperVignette: false,
  paperVignetteColor: '#3a2a14',
  paperVignetteIntensity: 0.45,
  paperVignetteRadius: 0.4,
  paperCompass: false,
  paperCompassLat: 32,
  paperCompassLng: -38,
  paperCompassColor: '#5b3a1f',
  paperCompassOpacity: 0.55,
  paperCompassSize: 8,
  paperAging: false,
  paperAgingCount: 12,
  paperAgingColor: '#7a5a2c',
  paperAgingIntensity: 0.22,
  paperAgingSeed: 1,
  paperWatermark: false,
  paperWatermarkText: 'ATLAS',
  paperWatermarkColor: '#5b3a1f',
  paperWatermarkOpacity: 0.18,
  paperWatermarkSize: 28,
  paperWatermarkPosition: 'bottomRight',
  /* ───────── Wireframe defaults ───────── */
  wireframeColor: '',
  wireframeOpacity: 0,
  wireframeDensity: 1,
  wireframePulse: 0,
  wireframePulseSpeed: 0.5,
  wireframeHierarchy: true,
  wireframeHierarchyMajorStepDeg: 30,
  wireframeHierarchyMajorBoost: 1.6,
  wireframeHierarchyMinorBoost: 0.85,
  wireframeClickPulse: true,
  wireframeClickPulseColor: '',
  wireframeClickPulseSpeed: 1.5,
  wireframeClickPulseWidth: 0.18,
  wireframeClickPulseBoost: 2.5,
  wireframeClickPulseMaxConcurrent: 4,
  wireframeEmphasis: true,
  wireframeEmphasisStrongColor: '',
  wireframeEmphasisWeakColor: '',
  wireframeEmphasisStrongOpacity: 0,
  wireframeEmphasisWeakOpacityFactor: 0.5,
  wireframeEquatorBeam: true,
  wireframeEquatorBeamColor: '',
  wireframeEquatorBeamOpacity: 0.85,
  wireframeEquatorBeamPulse: true,
  wireframeEquatorBeamPulseSpeed: 0.6,
  wireframeGlitch: true,
  wireframeGlitchIntervalMin: 5,
  wireframeGlitchIntervalMax: 15,
  wireframeActiveRing: true,
  wireframeActiveRingColor: '',
  wireframeActiveRingOpacity: 0,
  wireframeActiveRingPadding: 1.2,
  wireframeActiveRingRotationSpeed: 0.5,
  wireframePoleStreams: true,
  wireframePoleStreamsColor: '',
  wireframePoleStreamsOpacity: 0,
  wireframePoleStreamsCount: 16,
  wireframePoleStreamsSpeed: 0.6,
  wireframePoleStreamsSize: 0,
  wireframeDataPackets: true,
  wireframeDataPacketsColor: '',
  wireframeDataPacketsCount: 24,
  wireframeDataPacketsSpeed: 0.9,
  wireframeDataPacketsTrail: 0.18,
  wireframeDataPacketsSize: 0.018,
  wireframeDataPacketsAxis: 'both',
  wireframeCompass: true,
  wireframeCompassColor: '',
  wireframeCompassSize: 0.075,
  wireframeCompassOpacity: 0.9,
  wireframeCompassPoles: true,
  wireframeGridPulse: false,
  wireframeGridPulseColor: '',
  wireframeGridPulseIntervalSec: 4,
  wireframeGridPulseSpeed: 1.2,
  wireframeGridPulseWidth: 0.16,
  wireframeGridPulseBoost: 1.8,
  wireframeGridPulseMode: 'fixed',
  wireframeGridPulseOriginLat: 0,
  wireframeGridPulseOriginLng: 0,
  wireframePolePulse: false,
  wireframePolePulseColor: '',
  wireframePolePulseIntervalSec: 5,
  wireframePolePulseSpeed: 1,
  wireframePolePulseBoost: 1.5,
  wireframePolePulseWhich: 'both',
  clickToFocus: true,
  focusPadding: 0.15,
  focusDurationMs: 1500,
  focusElevation: 0,
  focusPauseAutoRotate: true,
  zoomMode: 'attract',
  zoomStrength: 0.7,
  smoothZoom: true,
  minZoom: 1.25,
  maxZoom: 7.5,
  initialLat: 18,
  initialLng: 38,
  pixelRatio: 'auto',
  adaptiveQuality: true,
  antialias: true,
  maxFps: 60,
};

export const defaultHeatmapSettings: HeatmapSettings = {
  dataset: 'countries',
  kernel: 'dome',
  normalize: 'absolute',
  curve: 'smoothstep',
  displacementCurve: 'cubic',
  palette: 'aurora',
  blendMode: 'normal',
  surfaceMode: 'country',
  detailMode: 'topo',
  radius: 0.075,
  maxHeight: 0.15,
  intensity: 1.6,
  threshold: 0.04,
  blurPasses: 1,
  shading: 0.74,
  meshLevel: 1,
  textureLevel: 1,
  domeCenterArea: 0.85,
  domeShoulderHeight: 0.83,
  domeEdgeSteepness: 1.4,
  domePreScale: 'log',
  animationEnabled: true,
  animationStyle: 'rise',
  animationOrder: 'sequential',
  animationEasing: 'ease-out-cubic',
  animationDurationMs: 1200,
  animationStaggerMs: 10,
  animationDelayMs: 0,
};

export const heatmapSurfacePresets: Readonly<Record<HeatmapSurfaceMode, Partial<HeatmapSettings>>> = {
  country: {
    dataset: 'countries',
    kernel: 'dome',
    normalize: 'absolute',
    curve: 'smoothstep',
    displacementCurve: 'cubic',
    palette: 'aurora',
    blendMode: 'normal',
    detailMode: 'topo',
    radius: 0.075,
    maxHeight: 0.15,
    intensity: 1.6,
    threshold: 0.04,
    blurPasses: 1,
    shading: 0.74,
    meshLevel: 1,
  },
  topographic: {
    kernel: 'gaussian',
    normalize: 'peak',
    curve: 'smoothstep',
    displacementCurve: 'smoothstep',
    palette: 'inferno',
    blendMode: 'normal',
    detailMode: 'topo',
    radius: 0.09,
    maxHeight: 0.12,
    intensity: 1.05,
    threshold: 0.04,
    blurPasses: 3,
    shading: 0.58,
    meshLevel: 1,
  },
  smooth: {
    kernel: 'gaussian',
    normalize: 'log',
    curve: 'sqrt',
    displacementCurve: 'sqrt',
    palette: 'aurora',
    blendMode: 'normal',
    detailMode: 'grid',
    radius: 0.17,
    maxHeight: 0.028,
    intensity: 0.96,
    threshold: 0,
    blurPasses: 5,
    shading: 0.22,
    meshLevel: 0,
  },
  peaks: {
    kernel: 'quartic',
    normalize: 'log',
    curve: 'cubic',
    displacementCurve: 'smoothstep',
    palette: 'inferno',
    blendMode: 'additive',
    detailMode: 'clean',
    radius: 0.055,
    maxHeight: 0.035,
    intensity: 1.45,
    threshold: 0.07,
    blurPasses: 1,
    shading: 0.15,
    meshLevel: 0,
  },
};

export const defaultState: ConfiguratorState = {
  activeLayer: 'hexbin',
  lastPresetId: null,
  dirtySincePreset: false,
  globe: defaultGlobeSettings,
  heatmap: defaultHeatmapSettings,
  hexbin: {
    dataset: 'cluster',
    resolution: 3,
    aggregate: 'count',
    heightMax: 0.085,
    cellInset: 0.97,
    opacity: 0.94,
    showEmpty: true,
    borders: false,
    borderOpacity: 0.3,
    highlight: true,
    animationEnabled: true,
    animationStyle: 'rise',
    animationOrder: 'radial',
    animationEasing: 'ease-out-cubic',
    animationDurationMs: 1300,
    animationStaggerMs: 2.5,
  },
  charts: {
    dataset: 'energy',
    chartType: 'bars-grouped',
    size: 0.06,
    height: 0.1,
    innerRadius: 0.45,
    padAngle: 0.02,
    labels: 'hover',
    borders: false,
    highlight: true,
    animationEnabled: true,
    animationOrder: 'sequential',
    animationEasing: 'ease-out-back',
    animationDurationMs: 900,
    animationStaggerMs: 35,
    segmentStaggerMs: 60,
  },
};

const layerFromPath = (pathname: string): ActiveLayer => {
  if (pathname.includes('heatmap')) return 'heatmap';
  if (pathname.includes('charts')) return 'charts';
  if (pathname.includes('hexbin')) return 'hexbin';
  return 'hexbin';
};

export const initialStateForPath = (pathname: string): ConfiguratorState => ({
  ...defaultState,
  activeLayer: layerFromPath(pathname),
});

export const configuratorPresets: ReadonlyArray<{
  readonly id: string;
  readonly label: string;
  readonly patch: Partial<ConfiguratorState>;
}> = [
  {
    id: 'hexbin-ops',
    label: 'Hexbin operations',
    patch: {
      activeLayer: 'hexbin',
      globe: { ...defaultGlobeSettings, theme: 'outline-dark', kind: 'outline' },
      hexbin: { ...defaultState.hexbin, dataset: 'cluster', aggregate: 'count', resolution: 3 },
    },
  },
  {
    id: 'heatmap-population',
    label: 'Population relief',
    patch: {
      activeLayer: 'heatmap',
      globe: { ...defaultGlobeSettings, theme: 'outline-dark', kind: 'outline', atmosphere: false },
      heatmap: { ...defaultHeatmapSettings, ...heatmapSurfacePresets.country, surfaceMode: 'country' },
    },
  },
  {
    id: 'charts-economy',
    label: 'Economy charts',
    patch: {
      activeLayer: 'charts',
      globe: { ...defaultGlobeSettings, theme: 'outline-dark', kind: 'outline' },
      charts: {
        ...defaultState.charts,
        chartType: 'extruded',
        dataset: 'world-gdp',
        labels: 'off',
        animationOrder: 'value',
      },
    },
  },
  {
    id: 'hologram-sensors',
    label: 'Hologram sensors',
    patch: {
      activeLayer: 'hexbin',
      globe: {
        ...defaultGlobeSettings,
        kind: 'hologram',
        theme: 'hologram-cyan',
        atmosphere: true,
        starfield: true,
      },
      hexbin: { ...defaultState.hexbin, dataset: 'random-2k', aggregate: 'sum', showEmpty: false },
    },
  },
];
